[project]
name = "house-of-silent-agents"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "openai>=1.61.0",
    "python-dotenv>=1.0.1",
]
